
server:
  port: 0

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ls-0c680c2adbc7c152941c70c39a18994bd30480ef.cpd3bfmvavpa.ap-northeast-2.rds.amazonaws.com:5432/productservice
    username: dbmasteruser
    password: testwinemall
  jpa:
    hibernate:
      ddl-auto: update
# NOTE: < 테스트 데이터 추가 >
#      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
# NOTE: < 테스트 데이터 추가 >
#    defer-datasource-initialization: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:testdata.sql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #Eureka Server ??
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.wine: DEBUG  # 귀하의 애플리케이션 패키지

