server:
  port: 8000
  application:
    name: apigate

spring:
  application:
    name: apigate
  cloud:
    gateway:
      #      httpclient:
      #        connect-timeout: 2000
      #        response-timeout: 2s
      #      mvc:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/**
          filters:
            - CustomFilter
            - RewritePath=/order-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defalutZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}

