server:
  port: 8000
  application:
    name: apigate

spring:
  application:
    name: apigate
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
            - CustomFilter
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
            - RewritePath=/product-service/(?<segment>.*), /$\{segment}
            - CustomFilter
            - name: AuthorizationHeaderFilter
              args:
                headerName: Authorization
                granted: Bearer

#      routes:
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/order-service/**
#          filters:
#            - CustomFilter
#            - RewritePath=/order-service/(?<segment>.*), /$\{segment}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
